version: "3.9"

services:
  backend:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vedat-ex-1
    restart: always
    env_file:
      - .env
    ports:
      - "80:80"
    volumes:
      - .:/app
